#include "Param.h"

#include <boost/property_tree/xml_parser.hpp>
#include <iostream>
#include <string>
#include <math.h>

namespace pt = boost::property_tree;
namespace QSP_IO{
using std::string;
using std::vector;

#define PARAM_DESCRIPTION_FIELD_COUNT 3
const char* _description[][PARAM_DESCRIPTION_FIELD_COUNT] =
{
    //simulation settings
    {"QSP.simulation.start","",""},//0
    {"QSP.simulation.step","",""},//1
    {"QSP.simulation.n_step","",""},//2
    {"QSP.simulation.tol_rel","",""},//3
    {"QSP.simulation.tol_abs","",""},//4
    //compartments
    {"QSP.init_value.Compartment.Cent","",""},//5|5
    {"QSP.init_value.Compartment.Peri","",""},//6|6
    {"QSP.init_value.Compartment.Tum","",""},//7|7
    {"QSP.init_value.Compartment.LN","",""},//8|8
    {"QSP.init_value.Compartment.mAPC_Endo","",""},//9|9
    {"QSP.init_value.Compartment.mAPC_Surf","",""},//10|10
    //species
    {"QSP.init_value.Species.Cent_Nivo","",""},//11|11
    {"QSP.init_value.Species.Cent_nT_CD8","",""},//12|12
    {"QSP.init_value.Species.Cent_nT_CD4","",""},//13|13
    {"QSP.init_value.Species.Cent_Treg","",""},//14|14
    {"QSP.init_value.Species.Cent_Teff_1_0","",""},//15|15
    {"QSP.init_value.Species.Peri_Nivo","",""},//16|16
    {"QSP.init_value.Species.Peri_Treg","",""},//17|17
    {"QSP.init_value.Species.Peri_Teff_1_0","",""},//18|18
    {"QSP.init_value.Species.Tum_Nivo","",""},//19|19
    {"QSP.init_value.Species.Tum_C1","",""},//20|20
    {"QSP.init_value.Species.Tum_Cp","",""},//21|21
    {"QSP.init_value.Species.Tum_DAMP","",""},//22|22
    {"QSP.init_value.Species.Tum_APC","",""},//23|23
    {"QSP.init_value.Species.Tum_mAPC","",""},//24|24
    {"QSP.init_value.Species.Tum_Ckine_Mat","",""},//25|25
    {"QSP.init_value.Species.Tum_Treg","",""},//26|26
    {"QSP.init_value.Species.Tum_Teff_PD1","",""},//27|27
    {"QSP.init_value.Species.Tum_Teff_PD1_syn","",""},//28|28
    {"QSP.init_value.Species.Tum_Teff_PD1_Nivo","",""},//29|29
    {"QSP.init_value.Species.Tum_Teff_PD1_Nivo_syn","",""},//30|30
    {"QSP.init_value.Species.Tum_Teff_PD1_Nivo_PD1_syn","",""},//31|31
    {"QSP.init_value.Species.Tum_C1_PDL1","",""},//32|32
    {"QSP.init_value.Species.Tum_C1_PDL1_syn","",""},//33|33
    {"QSP.init_value.Species.Tum_C1_PDL2","",""},//34|34
    {"QSP.init_value.Species.Tum_C1_PDL2_syn","",""},//35|35
    {"QSP.init_value.Species.Tum_C1_PDL1_Teff_PD1","",""},//36|36
    {"QSP.init_value.Species.Tum_C1_PDL2_Teff_PD1","",""},//37|37
    {"QSP.init_value.Species.Tum_D1_0","",""},//38|38
    {"QSP.init_value.Species.Tum_Teff_1_0","",""},//39|39
    {"QSP.init_value.Species.Tum_Teff_exhausted","",""},//40|40
    {"QSP.init_value.Species.LN_Nivo","",""},//41|41
    {"QSP.init_value.Species.LN_APC","",""},//42|42
    {"QSP.init_value.Species.LN_mAPC","",""},//43|43
    {"QSP.init_value.Species.LN_nT_CD8","",""},//44|44
    {"QSP.init_value.Species.LN_nT_CD4","",""},//45|45
    {"QSP.init_value.Species.LN_aTreg_CD4","",""},//46|46
    {"QSP.init_value.Species.LN_Treg","",""},//47|47
    {"QSP.init_value.Species.LN_IL2","",""},//48|48
    {"QSP.init_value.Species.LN_TCR_p1_0_M","",""},//49|49
    {"QSP.init_value.Species.LN_Cp","",""},//50|50
    {"QSP.init_value.Species.LN_D1_0","",""},//51|51
    {"QSP.init_value.Species.LN_aT_1_0","",""},//52|52
    {"QSP.init_value.Species.LN_Teff_1_0","",""},//53|53
    {"QSP.init_value.Species.mAPC_Endo_Cp","",""},//54|54
    {"QSP.init_value.Species.mAPC_Endo_cpt","",""},//55|55
    {"QSP.init_value.Species.mAPC_Endo_M1","",""},//56|56
    {"QSP.init_value.Species.mAPC_Endo_cpt_M1","",""},//57|57
    {"QSP.init_value.Species.mAPC_Endo_D1_0","",""},//58|58
    {"QSP.init_value.Species.mAPC_Endo_p1_0","",""},//59|59
    {"QSP.init_value.Species.mAPC_Endo_p1_0_M1","",""},//60|60
    {"QSP.init_value.Species.mAPC_Surf_cpt_M1","",""},//61|61
    {"QSP.init_value.Species.mAPC_Surf_M1","",""},//62|62
    {"QSP.init_value.Species.mAPC_Surf_cpt_M","",""},//63|63
    {"QSP.init_value.Species.mAPC_Surf_p1_0_M1","",""},//64|64
    {"QSP.init_value.Species.mAPC_Surf_p1_0_M","",""},//65|65
    //parameters
    {"QSP.init_value.Parameter.AvogadroN","",""},//66|66
    {"QSP.init_value.Parameter.cell","",""},//67|67
    {"QSP.init_value.Parameter.pat_weight","",""},//68|68
    {"QSP.init_value.Parameter.pat_density","",""},//69|69
    {"QSP.init_value.Parameter.pat_volume","",""},//70|70
    {"QSP.init_value.Parameter.f_w_peri","",""},//71|71
    {"QSP.init_value.Parameter.vol_LN_single","",""},//72|72
    {"QSP.init_value.Parameter.nLN","",""},//73|73
    {"QSP.init_value.Parameter.vol_cent","",""},//74|74
    {"QSP.init_value.Parameter.vol_peri","",""},//75|75
    {"QSP.init_value.Parameter.vol_tum","",""},//76|76
    {"QSP.init_value.Parameter.vol_LN","",""},//77|77
    {"QSP.init_value.Parameter.vol_tum_max","",""},//78|78
    {"QSP.init_value.Parameter.vol_tum_app","",""},//79|79
    {"QSP.init_value.Parameter.D_tum_app","",""},//80|80
    {"QSP.init_value.Parameter.D_tum_app_0","",""},//81|81
    {"QSP.init_value.Parameter.D_tum_app_percent","",""},//82|82
    {"QSP.init_value.Parameter.f_vol_cent","",""},//83|83
    {"QSP.init_value.Parameter.f_vol_peri","",""},//84|84
    {"QSP.init_value.Parameter.f_vol_tum","",""},//85|85
    {"QSP.init_value.Parameter.f_vol_LN","",""},//86|86
    {"QSP.init_value.Parameter.f_vol_BV","",""},//87|87
    {"QSP.init_value.Parameter.D_C","",""},//88|88
    {"QSP.init_value.Parameter.D_T","",""},//89|89
    {"QSP.init_value.Parameter.D_APC","",""},//90|90
    {"QSP.init_value.Parameter.vol_C","",""},//91|91
    {"QSP.init_value.Parameter.vol_T","",""},//92|92
    {"QSP.init_value.Parameter.vol_APC","",""},//93|93
    {"QSP.init_value.Parameter.A_C","",""},//94|94
    {"QSP.init_value.Parameter.A_T","",""},//95|95
    {"QSP.init_value.Parameter.A_APC","",""},//96|96
    {"QSP.init_value.Parameter.A_syn","",""},//97|97
    {"QSP.init_value.Parameter.d_syn","",""},//98|98
    {"QSP.init_value.Parameter.C1_min","",""},//99|99
    {"QSP.init_value.Parameter.C_presence","",""},//100|100
    {"QSP.init_value.Parameter.k_C_growth","",""},//101|101
    {"QSP.init_value.Parameter.K_C_max","",""},//102|102
    {"QSP.init_value.Parameter.k_C_death","",""},//103|103
    {"QSP.init_value.Parameter.k_C_death_by_T","",""},//104|104
    {"QSP.init_value.Parameter.Therapy","",""},//105|105
    {"QSP.init_value.Parameter.k_C_death_by_Therapy","",""},//106|106
    {"QSP.init_value.Parameter.D_per_C","",""},//107|107
    {"QSP.init_value.Parameter.Cp_per_C","",""},//108|108
    {"QSP.init_value.Parameter.DAMP_per_C","",""},//109|109
    {"QSP.init_value.Parameter.k_deg_D","",""},//110|110
    {"QSP.init_value.Parameter.t_resection","",""},//111|111
    {"QSP.init_value.Parameter.C1_resection","",""},//112|112
    {"QSP.init_value.Parameter.Teff_resection","",""},//113|113
    {"QSP.init_value.Parameter.Treg_resection","",""},//114|114
    {"QSP.init_value.Parameter.perm_CP_Ab","",""},//115|115
    {"QSP.init_value.Parameter.perm_CT_Ab","",""},//116|116
    {"QSP.init_value.Parameter.perm_CL_Ab","",""},//117|117
    {"QSP.init_value.Parameter.S_CP","",""},//118|118
    {"QSP.init_value.Parameter.S_CT","",""},//119|119
    {"QSP.init_value.Parameter.S_CL","",""},//120|120
    {"QSP.init_value.Parameter.Q_TL","",""},//121|121
    {"QSP.init_value.Parameter.Kd_Nivo","",""},//122|122
    {"QSP.init_value.Parameter.k_on_Nivo","",""},//123|123
    {"QSP.init_value.Parameter.k_off_Nivo","",""},//124|124
    {"QSP.init_value.Parameter.MW_Nivo","",""},//125|125
    {"QSP.init_value.Parameter.dose_mg_Nivo","",""},//126|126
    {"QSP.init_value.Parameter.dose_Nivo","",""},//127|127
    {"QSP.init_value.Parameter.Ki","",""},//128|128
    {"QSP.init_value.Parameter.k_on1_Nivo","",""},//129|129
    {"QSP.init_value.Parameter.k_off1_Nivo","",""},//130|130
    {"QSP.init_value.Parameter.k_on2_Nivo","",""},//131|131
    {"QSP.init_value.Parameter.k_off2_Nivo","",""},//132|132
    {"QSP.init_value.Parameter.t_init_Nivo","",""},//133|133
    {"QSP.init_value.Parameter.t_inter_Nivo","",""},//134|134
    {"QSP.init_value.Parameter.n_dose_Nivo","",""},//135|135
    {"QSP.init_value.Parameter.t_infus_Nivo","",""},//136|136
    {"QSP.init_value.Parameter.t_off_Nivo","",""},//137|137
    {"QSP.init_value.Parameter.t_on_Nivo","",""},//138|138
    {"QSP.init_value.Parameter.count_dose_Nivo","",""},//139|139
    {"QSP.init_value.Parameter.k_infus_Nivo","",""},//140|140
    {"QSP.init_value.Parameter.cl_Nivo","",""},//141|141
    {"QSP.init_value.Parameter.f_vol_peri_Nivo","",""},//142|142
    {"QSP.init_value.Parameter.P_ratio_Nivo","",""},//143|143
    {"QSP.init_value.Parameter.f_vol_cent_Nivo","",""},//144|144
    {"QSP.init_value.Parameter.Teff_PD1_tot","",""},//145|145
    {"QSP.init_value.Parameter.C1_PDL1_tot","",""},//146|146
    {"QSP.init_value.Parameter.C1_PDL2_tot","",""},//147|147
    {"QSP.init_value.Parameter.Kd_PD1_PDL1","",""},//148|148
    {"QSP.init_value.Parameter.k_on_PD1_PDL1","",""},//149|149
    {"QSP.init_value.Parameter.k_off_PD1_PDL1","",""},//150|150
    {"QSP.init_value.Parameter.K_C1_PDLX_Teff_PD1","",""},//151|151
    {"QSP.init_value.Parameter.Kd_PD1_PDL2","",""},//152|152
    {"QSP.init_value.Parameter.k_on_PD1_PDL2","",""},//153|153
    {"QSP.init_value.Parameter.k_off_PD1_PDL2","",""},//154|154
    {"QSP.init_value.Parameter.n_PD1_PDLX","",""},//155|155
    {"QSP.init_value.Parameter.V_E","",""},//156|156
    {"QSP.init_value.Parameter.V_intake","",""},//157|157
    {"QSP.init_value.Parameter.p_per_P","",""},//158|158
    {"QSP.init_value.Parameter.k_int_Cp","",""},//159|159
    {"QSP.init_value.Parameter.k_deg_Cp","",""},//160|160
    {"QSP.init_value.Parameter.k_deg_cpt","",""},//161|161
    {"QSP.init_value.Parameter.k_deg_cpt_M","",""},//162|162
    {"QSP.init_value.Parameter.k_int_Dend","",""},//163|163
    {"QSP.init_value.Parameter.k_deg_Dend","",""},//164|164
    {"QSP.init_value.Parameter.k_deg_p","",""},//165|165
    {"QSP.init_value.Parameter.k_deg_p_M","",""},//166|166
    {"QSP.init_value.Parameter.M1_0","",""},//167|167
    {"QSP.init_value.Parameter.k_deg_M","",""},//168|168
    {"QSP.init_value.Parameter.k_int_M","",""},//169|169
    {"QSP.init_value.Parameter.k_ext_p_M","",""},//170|170
    {"QSP.init_value.Parameter.n_clone_Treg","",""},//171|171
    {"QSP.init_value.Parameter.n_clone_p1_0","",""},//172|172
    {"QSP.init_value.Parameter.Kd_p1_0_M1","",""},//173|173
    {"QSP.init_value.Parameter.k_on_p1_0_M1","",""},//174|174
    {"QSP.init_value.Parameter.k_off_p1_0_M1","",""},//175|175
    {"QSP.init_value.Parameter.Kd_cpt_M1","",""},//176|176
    {"QSP.init_value.Parameter.k_on_cpt_M1","",""},//177|177
    {"QSP.init_value.Parameter.k_off_cpt_M1","",""},//178|178
    {"QSP.init_value.Parameter.k_ext_cpt_M","",""},//179|179
    {"QSP.init_value.Parameter.APC0_Tum","",""},//180|180
    {"QSP.init_value.Parameter.APC0_LN","",""},//181|181
    {"QSP.init_value.Parameter.k_APC_death","",""},//182|182
    {"QSP.init_value.Parameter.k_mAPC_death","",""},//183|183
    {"QSP.init_value.Parameter.Ckine_Mat0","",""},//184|184
    {"QSP.init_value.Parameter.k_Ckine_Mat_deg","",""},//185|185
    {"QSP.init_value.Parameter.K_Ckine_Mat_Cp","",""},//186|186
    {"QSP.init_value.Parameter.k_APC_mat","",""},//187|187
    {"QSP.init_value.Parameter.K_APC_mat","",""},//188|188
    {"QSP.init_value.Parameter.k_mAPC_mig","",""},//189|189
    {"QSP.init_value.Parameter.nT_CD8_dens","",""},//190|190
    {"QSP.init_value.Parameter.nT_CD4_dens","",""},//191|191
    {"QSP.init_value.Parameter.k_nT_entry","",""},//192|192
    {"QSP.init_value.Parameter.k_nT_exit","",""},//193|193
    {"QSP.init_value.Parameter.nT_CD8_diver","",""},//194|194
    {"QSP.init_value.Parameter.nT_CD4_diver","",""},//195|195
    {"QSP.init_value.Parameter.k_nTCD8_mAPC","",""},//196|196
    {"QSP.init_value.Parameter.n_sites_mAPC","",""},//197|197
    {"QSP.init_value.Parameter.K_p_M","",""},//198|198
    {"QSP.init_value.Parameter.k_aT_prolif","",""},//199|199
    {"QSP.init_value.Parameter.k_Teff_death","",""},//200|200
    {"QSP.init_value.Parameter.k_Teff_death_peri","",""},//201|201
    {"QSP.init_value.Parameter.k_Teff_death_by_C","",""},//202|202
    {"QSP.init_value.Parameter.k_Teff_egress","",""},//203|203
    {"QSP.init_value.Parameter.k_Teff_transmig","",""},//204|204
    {"QSP.init_value.Parameter.k_Teff_exit","",""},//205|205
    {"QSP.init_value.Parameter.S_adhesion_tot","",""},//206|206
    {"QSP.init_value.Parameter.S_adhesion_peri_tot","",""},//207|207
    {"QSP.init_value.Parameter.S_adhesion","",""},//208|208
    {"QSP.init_value.Parameter.S_adhesion_peri","",""},//209|209
    {"QSP.init_value.Parameter.T_all_Cent","",""},//210|210
    {"QSP.init_value.Parameter.T_all_Tum","",""},//211|211
    {"QSP.init_value.Parameter.clonality","",""},//212|212
    {"QSP.init_value.Parameter.n_aT_prolif_TCR0","",""},//213|213
    {"QSP.init_value.Parameter.n_aT_prolif_IL20","",""},//214|214
    {"QSP.init_value.Parameter.n_aT_prolif_Coestim0","",""},//215|215
    {"QSP.init_value.Parameter.K_IL2_Teff","",""},//216|216
    {"QSP.init_value.Parameter.k_IL2_rel","",""},//217|217
    {"QSP.init_value.Parameter.k_IL2_deg","",""},//218|218
    {"QSP.init_value.Parameter.k_IL2_consump","",""},//219|219
    {"QSP.init_value.Parameter.n_aT_prolif_TCR","",""},//220|220
    {"QSP.init_value.Parameter.n_aT_prolif_IL2","",""},//221|221
    {"QSP.init_value.Parameter.n_aT_prolif_Coestim","",""},//222|222
    {"QSP.init_value.Parameter.n_aT_prolif","",""},//223|223
    {"QSP.init_value.Parameter.k_nTCD4_APC","",""},//224|224
    {"QSP.init_value.Parameter.n_sites_APC","",""},//225|225
    {"QSP.init_value.Parameter.K_Cp","",""},//226|226
    {"QSP.init_value.Parameter.k_aTreg_prolif","",""},//227|227
    {"QSP.init_value.Parameter.K_IL2_Treg","",""},//228|228
    {"QSP.init_value.Parameter.nTreg_basal","",""},//229|229
    {"QSP.init_value.Parameter.k_Treg_death","",""},//230|230
    {"QSP.init_value.Parameter.k_Treg_egress","",""},//231|231
    {"QSP.init_value.Parameter.k_Treg_transmig","",""},//232|232
    {"QSP.init_value.Parameter.k_Treg_exit","",""},//233|233
    {"QSP.init_value.Parameter.k_Teff_inhibBy_Treg","",""},//234|234
    {"QSP.init_value.Parameter.K_Treg_inhib","",""},//235|235
    {"QSP.init_value.Parameter.n_Treg_prolif_IL2","",""},//236|236
    {"QSP.init_value.Parameter.Teff2TregRatio","",""},//237|237
    {"QSP.init_value.Parameter.k_Teff_exh_death","",""},//238|238
    {"QSP.init_value.Parameter.n_Treg_prolif_IL20","",""},//239|239
};

Param::Param()
    :ParamBase()
{
    setupParam();
}

void Param::setupParam(){
    for (size_t i = 0; i < 240; i++)
    {
        _paramDesc.push_back(vector<string>(_description[i], 
            _description[i]+ PARAM_DESCRIPTION_FIELD_COUNT));
		// combine paramter files
		_paramDesc[i][0] = "Param." + _paramDesc[i][0];
    }
    _paramFloat = vector<double>(240, 0);
}

};
